const availableTags = [
    'API',
    'Frontend',
    'Backend',
    'Database',
    'Authentication',
    'React',
    'Next.js',
    'Node.js',
    'Express',
    'MongoDB',
    'SQL',
    'CSS',
    'TypeScript',
    'Discord',
    'Game Development',
    'Testing',
    'DevOps',
    'AWS',
    'Security',
    'Performance',
    'Mobile',
    'Desktop',
    'UI/UX',
    'Animation',
    'Machine Learning',
];

export default availableTags;